### PR TITLE
Add two new prefs

### PR DESCRIPTION
**Pull request by tumpio**
Hello!

Added two new prefs that I think should be included.

devtools.debugger.prompt-connection to disable connection permission prompts
and
xpinstall.signatures.required to disable extension signature check

Thank you for creating this addon! It really helps to set up new development profile!

### CODE REVIEW

**Comment by tumpio** [comment]
Noticed that the xpinstall.signatures.required setting did not apply and found the reason. There was little bug in the addon to break instead of continue in the config loop.

**Comment by Noitidart** [comment]
Thank you @tumpio - merged it in. :) Will upload to AMO.

**Comment by Noitidart** [comment]
Hey @tumpio are you in Finland (or do you know anyone in Finland) by any my friend needs to fake out a website and log in from Finland, and he couldn't get proxies to work. haha I know weird request. But if you are in Finland it would be soooo awesome if you can help me out :D

**Comment by Noitidart** [comment]
Oh never mind he got it. Thanks Tumpio for reading!

**Pull request merged**
